import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
// import { useRouter } from 'next/navigation'
// import { getAuth, createUserWithEmailAndPassword } from 'firebase/auth'
// import { useState, useEffect } from 'react'
import { AuthProvider } from '@/features/context/AuthContext'
import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/Footer'
import Layout from '@/components/layout/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'travel-plan-app',
  description: 'Generated by create next app',
  applicationName: 'travel-plan-app',
  keywords: ['travel-plan-app'],
  // openGraph: {
  //   title: 'Next.js',
  //   description: 'The React Framework for the Web',
  //   url: 'https://nextjs.org',
  //   siteName: 'Next.js',
  // }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <Layout>
            {/* <Header /> */}
            {children}
            {/* <Footer /> */}
          </Layout>
        </AuthProvider>
      </body>
    </html>
  )
}
