import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='text-gray-600 body-font bg-gray-100'>
          <div className='container mx-auto flex flex-wrap p-5 justify-between'>
            <div className='flex title-font font-medium items-center text-gray-900 md:mb-0'>
              <h1 className='ml-3 text-xl font-bold'>
                <Link href='/projects/' className=''>
                  TRAVEL PLAN APP
                </Link>
              </h1>
            </div>
            <nav className='md:ml-auto flex flex-wrap items-center text-base justify-end'>
              <button className='hover:bg-gray-200'>HELP</button>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
